concerns:
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/arbitration/build/contracts/PartitionInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/arbitration/build/contracts/MMInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/arbitration/build/contracts/VGInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/arbitration/build/contracts/ComputeInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/tournament/build/contracts/MatchInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/tournament/build/contracts/MatchManagerInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
  - abi: "/opt/cartesi/share/blockchain/node_modules/@cartesi/tournament/build/contracts/RevealInstantiator.json"
    user_address: "${ACCOUNT_ADDRESS}"
main_concern:
  abi: "/opt/cartesi/share/blockchain/build/contracts/DApp.json"
  user_address: "${ACCOUNT_ADDRESS}"
confirmations: 12
max_delay: 500
query_port: 3001
services:
  - name: emulator
    transport:
      address: machine-manager
      port: 50051
  - name: logger
    transport:
      address: logger
      port: 50051
testing: true
url: ${ETHEREUM_URL}
warn_delay: 30
polling_interval: 15
web3_timeout: 10
