version: '3'
services:
  creepts-emulator:
    image: cartesi/creepts-emulator
    volumes:
      - emulator_data:/opt/cartesi/creepts
    entrypoint: ls -al

  creepts-onchain:
    image: cartesi/creepts-onchain
    volumes:
      - onchain_data:/opt/cartesi/share/blockchain

  dispatcher:
    image: cartesi/creepts
    depends_on: [creepts-onchain]
    environment:
      RUST_LOG: dispatcher=trace,transaction=trace,configuration=trace,utils=trace,state=trace,compute=trace,tournament=trace,creepts_dapp=trace
      ETHEREUM_URL: wss://rinkeby.infura.io/v3/93b4e1af3e524cf5979ca45262b4d81b
      ETHEREUM_HOST: rinkeby.infura.io
      ETHEREUM_PORT: 443
      NETWORK_ID: 4
      DOCKER: "true"
      MNEMONIC: "${MNEMONIC}"
      ACCOUNT_INDEX: 0
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - onchain_data:/opt/cartesi/share/blockchain

  logger:
    image: cartesi/logger-server:0.1.0
    depends_on: [creepts-onchain]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/logger-server
      - onchain_data:/opt/cartesi/share/blockchain
    environment:
      WEB3_PROVIDER_URI: wss://rinkeby.infura.io/v3/93b4e1af3e524cf5979ca45262b4d81b
      NETWORK_ID: 4
      MNEMONIC: "${MNEMONIC}"
  
  machine-manager:
    image: cartesi/machine-manager:0.1.0
    depends_on: [creepts-emulator]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - emulator_data:/opt/cartesi/srv/emulator-files
  
  anuto-server:
    image: cartesi/anuto-server:develop-f4103222
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
  
  web:
    depends_on: [anuto-server]
    image: cartesi/creepts-web
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "8090:80"
  
volumes:
  emulator_data:
  onchain_data:
  dapp_data:
