{% set players = num_players | int %}
version: '3'
services:
  geth:
    build: geth
    command: [ "--rpcvhosts=*", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcport", "8545", "--nodiscover", "--mine", "--networkid", "15", "--rpcapi", "eth,net,web3,personal", "--allow-insecure-unlock" ]
    expose:
      - 8545
    ports:
      - 8545:8545
    volumes:
      {% for i in range(players) %}- key_data_{{ i }}:/key-{{ i }}
      {% endfor %}
    networks:
      - ethereum

  deployer:
    depends_on: [geth]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      ETHEREUM_HOST: geth
      ETHEREUM_NETWORK: geth
      ETHEREUM_TIMEOUT: 60s
    volumes:
      - ./:/opt/cartesi/share/blockchain
    networks:
      - ethereum

  creepts_emulator:
    image: cartesi/creepts-machine:0.1.0
    volumes:
      - emulator_data:/opt/cartesi/creepts
    entrypoint: ls -al

{% for i in range(players) %}
  dispatcher_{{ i }}:
    # build: .
    image: cartesi/creepts:0.1.3
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info,compute=trace,tournament=trace,creepts_dapp=trace
      ETHEREUM_URL: http://geth:8545
      ETHEREUM_HOST: geth
      ETHEREUM_TIMEOUT: 240s
      DOCKER: "TRUE"
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - dispatcher
    ports:
      - "{{ 3001 + i }}:3001"
  
  logger_{{ i }}:
    image: cartesi/logger-server:0.1.1
    command: [ "-c", "/opt/cartesi/share/blockchain/node_modules/@cartesi/logger/build/contracts/Logger.json" ]
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/logger-server
    environment:
      WEB3_PROVIDER_URI: http://geth:8545
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - logger

  machine_manager_{{ i }}:
    image: cartesi/machine-manager:0.1.0
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
      - emulator_data:/opt/cartesi/srv/emulator-files
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - machine-manager

  backend_{{ i }}:
    image: cartesi/creepts-backend:0.1.4
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    environment:
      WEB3_PROVIDER_URI: http://geth:8545
      LOG_FILES_OUTPUT_DIR: /opt/cartesi/srv/creepts/
      DB_NAME: /opt/cartesi/srv/creepts/creepts.db
      CONTRACTS_DIR: /opt/cartesi/share/blockchain
    ports:
      - "{{ 8000 + i }}:8000"
    networks:
      node_{{ i }}:
        aliases:
          - backend

  web_{{ i }}:
    depends_on: [backend_{{ i }}]
    image: cartesi/creepts-web:0.1.3
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "{{ 8090 + i }}:80"
    networks:
      - node_{{ i }}
{% endfor %}

volumes:
  truffle_data:
  emulator_data:
  {% for i in range(players) %}dapp_data_{{ i }}:
  key_data_{{ i }}:
  {% endfor %}

networks:
  ethereum:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
