{% set players = num_players | int %}
version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.7.0
    command: ["ganache-cli", "--accounts", "{{ players }}", "--account_keys_path", "/ganache-data/keys"]
    volumes:
      - ganache_data:/ganache-data
    expose:
      - 8545
    ports:
      - 8545:8545
    networks:
      - ethereum

  deployer:
    depends_on: [ganache]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      ETHEREUM_HOST: ganache
      ETHEREUM_NETWORK: ganache
    volumes:
      - ./:/opt/cartesi/share/blockchain
    networks:
      - ethereum

  key_distributor:
    depends_on: [ganache]
    image: cartesi/key-distributor
    volumes:
      - ganache_data:/keys
      {% for i in range(players) %}- key_data_{{ i }}:/key-{{ i }}
      {% endfor %}

  creepts_emulator:
    image: cartesi/creepts-emulator:0.1.0-rc1
    volumes:
      - emulator_data:/opt/cartesi/creepts
    entrypoint: ls -al
  
{% for i in range(players) %}
  dispatcher_{{ i }}:
    image: cartesi/creepts
    environment:
      RUST_LOG: dispatcher=info,transaction=info,configuration=trace,utils=trace,state=info,compute=trace,tournament=trace,creepts_dapp=trace
      ETHEREUM_URL: http://ganache:8545
      DOCKER: "TRUE"
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - dispatcher
    ports:
      - "{{ 3001 + i }}:3001"

  logger_{{ i }}:
    image: cartesi/logger-server:0.1.0
    command: [ "-c", "/opt/cartesi/share/blockchain/node_modules/@cartesi/logger/build/contracts/Logger.json" ]
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/logger-server
    environment:
      WEB3_PROVIDER_URI: http://ganache:8545
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - logger

  machine_manager_{{ i }}:
    image: cartesi/machine-manager:0.1.0
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
      - emulator_data:/opt/cartesi/srv/emulator-files
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - machine-manager

  backend_{{ i }}:
    image: cartesi/creepts-backend
    volumes:
      - ./:/opt/cartesi/share/blockchain:ro
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    environment:
      WEB3_PROVIDER_URI: http://ganache:8545
      LOG_FILES_OUTPUT_DIR: /opt/cartesi/srv/creepts/
    ports:
      - "{{ 8000 + i }}:8000"
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - backend

  web_{{ i }}:
    depends_on: [backend_{{ i }}]
    image: cartesi/creepts-web
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "{{ 8090 + i }}:80"
    networks:
      - node_{{ i }}
{% endfor %}

volumes:
  ganache_data:
  emulator_data:
  {% for i in range(players) %}dapp_data_{{ i }}:
  key_data_{{ i }}:
  {% endfor %}

networks:
  ethereum:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
