version: '3'
services:
  creepts-emulator:
    image: cartesi/creepts-machine:0.2.0
    volumes:
      - emulator_data:/opt/cartesi/creepts
    entrypoint: ls -al

  creepts-onchain:
    image: cartesi/creepts-onchain:0.2.0
    volumes:
      - onchain_data:/opt/cartesi/share/blockchain

  dispatcher:
    image: cartesi/creepts:0.2.0
    restart: always
    depends_on: [creepts-onchain]
    environment:
      RUST_LOG: dispatcher=trace,transaction=trace,transport=trace,configuration=trace,utils=trace,state=trace,compute=trace,tournament=trace,creepts_dapp=trace
      WEB3_PROVIDER_URI: "${WEB3_PROVIDER_URI:?WEB3_PROVIDER_URI not set}"
      DOCKER: "TRUE"
      MNEMONIC: "${MNEMONIC:?MNEMONIC not set}"
      ACCOUNT_INDEX: 0
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - onchain_data:/opt/cartesi/share/blockchain

  logger:
    image: cartesi/logger-server:0.2.2
    command: [ "-c", "/opt/cartesi/share/blockchain/node_modules/@cartesi/logger/build/contracts/Logger.json" ]
    depends_on: [creepts-onchain]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/logger-server
      - onchain_data:/opt/cartesi/share/blockchain
    environment:
      WEB3_PROVIDER_URI: "${WEB3_PROVIDER_URI:?WEB3_PROVIDER_URI not set}"
      MNEMONIC: "${MNEMONIC:?MNEMONIC not set}"
  
  machine-manager:
    image: cartesi/machine-manager:0.3.0
    depends_on: [creepts-emulator]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - emulator_data:/opt/cartesi/srv/emulator-files
  
  backend:
    image: cartesi/creepts-backend:0.1.6
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - onchain_data:/opt/cartesi/share/blockchain
    environment:
      WEB3_PROVIDER_URI: "${WEB3_PROVIDER_URI:?WEB3_PROVIDER_URI not set}"
      LOG_FILES_OUTPUT_DIR: /opt/cartesi/srv/creepts/
      DB_NAME: /opt/cartesi/srv/creepts/creepts.db
      CONTRACTS_DIR: /opt/cartesi/share/blockchain
      MNEMONIC: "${MNEMONIC:?MNEMONIC not set}"
  
  web:
    depends_on: [backend]
    image: cartesi/creepts-web:0.1.5
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "8090:80"
  
volumes:
  emulator_data:
  onchain_data:
  dapp_data:
