version: '3'
services:
  creepts-emulator:
    image: cartesi/creepts-emulator:0.1.1
    volumes:
      - emulator_data:/opt/cartesi/creepts
    entrypoint: ls -al

  creepts-onchain:
    image: cartesi/creepts-onchain:0.1.0
    volumes:
      - onchain_data:/opt/cartesi/share/blockchain

  dispatcher:
    image: cartesi/creepts:0.1.1
    depends_on: [creepts-onchain]
    environment:
      RUST_LOG: dispatcher=trace,transaction=trace,transport=trace,configuration=trace,utils=trace,state=trace,compute=trace,tournament=trace,creepts_dapp=trace
      ETHEREUM_URL: wss://rinkeby.infura.io/ws/v3/93b4e1af3e524cf5979ca45262b4d81b
      ETHEREUM_HOST: rinkeby.infura.io
      ETHEREUM_PORT: 443
      NETWORK_ID: 4
      DOCKER: "TRUE"
      MNEMONIC: "${MNEMONIC}"
      ACCOUNT_INDEX: 0
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - onchain_data:/opt/cartesi/share/blockchain

  logger:
    image: cartesi/logger-server:0.1.1
    command: [ "-c", "/opt/cartesi/share/blockchain/node_modules/@cartesi/logger/build/contracts/Logger.json" ]
    depends_on: [creepts-onchain]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/logger-server
      - onchain_data:/opt/cartesi/share/blockchain
    environment:
      WEB3_PROVIDER_URI: wss://rinkeby.infura.io/ws/v3/93b4e1af3e524cf5979ca45262b4d81b
      NETWORK_ID: 4
      MNEMONIC: "${MNEMONIC}"
  
  machine-manager:
    image: cartesi/machine-manager:0.1.0
    depends_on: [creepts-emulator]
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - emulator_data:/opt/cartesi/srv/emulator-files
  
  backend:
    image: cartesi/creepts-backend:0.1.3
    volumes:
      - ./dapp_data:/opt/cartesi/srv/creepts
      - onchain_data:/opt/cartesi/share/blockchain
    environment:
      WEB3_PROVIDER_URI: wss://rinkeby.infura.io/ws/v3/93b4e1af3e524cf5979ca45262b4d81b
      LOG_FILES_OUTPUT_DIR: /opt/cartesi/srv/creepts/
      DB_NAME: /opt/cartesi/srv/creepts/creepts.db
      CONTRACTS_DIR: /opt/cartesi/share/blockchain
      NETWORK_ID: 4
      MNEMONIC: "${MNEMONIC}"
  
  web:
    depends_on: [backend]
    image: cartesi/creepts-web:0.1.2
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "8090:80"
  
volumes:
  emulator_data:
  onchain_data:
  dapp_data:
