{% set players = num_players | int %}
version: '3'
services:
  geth:
    build: geth
    command: [ "--rpcvhosts=*", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcport", "8545", "--nodiscover", "--mine", "--networkid", "15", "--rpcapi", "eth,net,web3,personal", "--allow-insecure-unlock" ]
    expose:
      - 8545
    volumes:
      {% for i in range(players) %}- key_data_{{ i }}:/key-{{ i }}
      {% endfor %}
    networks:
      - ethereum

  deployer:
    depends_on: [geth]
    build:
      context: .
      dockerfile: ./deployer/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      ETHEREUM_HOST: geth
      ETHEREUM_NETWORK: geth
      ETHEREUM_TIMEOUT: 60s
    volumes:
      - truffle_data:/usr/src/app/build
    networks:
      - ethereum

#  emulator_setup:
#    build: emulator_setup
#    volumes:
#      - emulator_data:/root/host
#    environment:
#      GITHUB_TOKEN: ${GITHUB_TOKEN}

{% for i in range(players) %}
  dispatcher_{{ i }}:
    # build: .
    image: cartesi/creepts
    environment:

      RUST_LOG: dispatcher=trace,transaction=trace,configuration=trace,utils=trace,state=trace,compute=trace,tournament=trace,anuto_dapp=trace
      ETHEREUM_URL: http://geth:8545
      ETHEREUM_HOST: geth
      ETHEREUM_TIMEOUT: 240s
      DOCKER: "true"
    volumes:
      - truffle_data:/opt/cartesi/share/blockchain
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    networks:
      - ethereum
      - node_{{ i }}

  logger_{{ i }}:
    image: cartesi/logger-server
    volumes:
      - truffle_data:/opt/cartesi/share/blockchain
      - key_data_{{ i }}:/opt/cartesi/etc/keys
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/logger-server
    environment:
      WEB3_PROVIDER_URI: http://geth:8545
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - logger

  machine_manager_{{ i }}:
    image: cartesi/machine-manager
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
      - ./emulator_data:/opt/cartesi/srv/emulator-files
    networks:
      ethereum: {}
      node_{{ i }}:
        aliases:
          - machine-manager

  anuto_server_{{ i }}:
    image: cartesi/anuto-server:develop-f4103222
    volumes:
      - ./dapp_data_{{ i }}:/opt/cartesi/srv/creepts
    networks:
      node_{{ i }}:
        aliases:
          - anuto-server

  web_{{ i }}:
    depends_on: [anuto_server_{{ i }}]
    image: cartesi/creepts-web
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "{{ 8090 + i }}:80"
    networks:
      - node_{{ i }}
{% endfor %}

volumes:
  truffle_data:
  emulator_data:
  {% for i in range(players) %}dapp_data_{{ i }}:
  key_data_{{ i }}:
  {% endfor %}

networks:
  ethereum:
  {% for i in range(players) %}node_{{ i }}:
  {% endfor %}
