#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo $0 "<input-log> <log-drive>"
    exit 1
fi

tmpdir=$(mktemp -d -t anuto-XXXXXXXXXX)
(cp $1 /$tmpdir/log.json; cd $tmpdir; brotli log.json; echo log.json.br | cpio -o -F log.json.cpio)
cp $tmpdir/log.json.cpio $2

\rm -rf  $tmpdir
