#!/bin/sh

tmpdir=$(mktemp -d -t anuto-XXXXXXXXXX)
(cp $1 /$tmpdir/log.json; cd $tmpdir; brotli log.json; tar -cf log.json.br.tar log.json.br)
cp $tmpdir/log.json.br.tar $2

if [ $(uname) = "Darwin" ]; then
    gtruncate -s %4096 $2
else
    truncate -s %4096 $2
fi

\rm -rf  $tmpdir
