name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - run: echo "::set-env name=TAG::${GITHUB_REF:11}"
        if: startsWith(github.ref, 'refs/tags/v')
    
      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull images for caching
        run: |
          docker pull cartesi/creepts:onchain || true
          docker pull cartesi/creepts:build || true
          docker pull cartesi/creepts:latest || true

      - name: Build
        run: |
          docker build . --target onchain --cache-from cartesi/creepts:onchain -t cartesi/creepts:onchain --build-arg TAG=${TAG} --build-arg NPM_TOKEN=${NPM_TOKEN}
          docker build . --target build --cache-from cartesi/creepts:onchain --cache-from cartesi/creepts:build -t cartesi/creepts:build --build-arg TAG=${TAG} --build-arg NPM_TOKEN=${NPM_TOKEN}
          docker build . --target runtime --cache-from cartesi/creepts:onchain --cache-from cartesi/creepts:build --cache-from cartesi/creepts:latest -t cartesi/creepts:${TAG} --build-arg TAG=${TAG} --build-arg NPM_TOKEN=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push to Docker Hub
        run: |
          docker push cartesi/creepts:onchain
          docker push cartesi/creepts:build
          docker push cartesi/creepts:${TAG}
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
